---
  - name: install packages
    apt: name={{item}}
    with_items:
        - htop
        - tmux
        - vim-nox
        - python3-psutil
        - dirmngr
        - gnupg
        - apt-transport-https
        - ca-certificates
        - software-properties-common
        - docker
        - docker-compose
        - kubectl
        - kubeadm
        - kubectl
        - net-tools
        - nmap
        - wireshark
        - aircrack-ng
        - airgraph-ng
        - arp-scan
        - wifite
        - tilix
        - vlc
        - gnome-tweaks
        - flameshot
        - neofetch
        - ncdu
        - cmus
        - golang
        - python3
        - python3-pip
